# Generated by Django 5.0.1 on 2024-01-17 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
