name: Quality Assurance

on:
  pull_request:
  workflow_call:

jobs:
  Quality-assurance:
    name: Quality Assurance
    runs-on: ubuntu-latest
    container:
      image: python:3.10.12-buster

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirement.txt

      - name: Lint Setup
        run: |
          python -m pip install pylint

      - name: Analyzing Code
        run: |
          find . -name '*.py' -exec pylint {} +
