name: Quality Assurance
on: [pull_request,workflow_call]

jobs:
    Quality-assurance:
        name: Quality Assurance
        runs-on: ubuntu-latest
        container: python:3.10.12-buster

    steps:
        - uses: actions/checkout@v2
        - name: Install PIP
          uses: BSFishy/pip-action@v1
          with:
            requirements: requirements.txt
        - name: Lint Setup
          run: python -m pip install pylint
        - name: Analysing Code
          run: |
            find . -name '*.py' -exec pylint {} \;

